// projects-demo/taro-mini-vue-demo/src/pages/index/index.vue
<template>
  <view class="index-demo">
    <nut-button type="primary">NutUI小程序组件库</nut-button>
    <text class="msg">{{ msg }}</text>
    <ProjectComponentDemo message="Hello Project VueComponentDemo"></ProjectComponentDemo>
    <VueDemoComponent message="Hello MonoRepo VueComponentDemo"></VueDemoComponent>
  </view>
</template>

<script>
import { ref } from 'vue'
import './index.scss'
import { testHelloMonoRepo } from 'athena-test'
import ProjectComponentDemo from '@/components/demo/ComponentDemo.vue'
import { CommonUtils } from 'athena-utils'
import { demoApi } from '@/api/demo/demo'
import { VueDemoComponent } from 'athena-components-vue'
import { Constant } from 'athena-constants'
import { Pipe, Validate } from 'athena-common'

export default {
  components: {
    ProjectComponentDemo,
    VueDemoComponent
  },

  setup() {
    const msg = ref('Hello Taro Mini Pnpm MonoRepo')
    return {
      msg
    }
  },

  onLoad() {
    console.log('Index onLoad')
  },

  onShow() {
    this.testMonoRepo()

  },

  methods: {
    testMonoRepo() {
      console.log('Taro多包复用示例')
      testHelloMonoRepo()
      demoApi().then(res => {

      })

      console.log(CommonUtils.randomString(6, 12))
      console.log(Pipe.hidePart('18863302302', 'phone'))
      console.log(Constant.PHONE_REGEX)
      console.log('校验结果: ' + Validate.email('123'))

    }

  }

}
</script>

// projects/taro-mini-demo/src/pages/index/index.tsx
import {Component} from 'react'
import {Text, View} from '@tarojs/components'
import './index.scss'
import {Pipe, Validate} from "athena-common";
import {CommonUtils} from "athena-utils";
import {Constant} from "athena-constants";
import {Demo} from "athena-components";
import {demoApi} from "../../api/login/demo";

export default class Index extends Component {

  componentWillMount() {
  }

  componentDidMount() {
    console.log('Taro多包复用示例')
    console.log(Pipe.hidePart('18863302302', 'phone'))
    console.log(CommonUtils.randomString(6, 12))
    console.log(Constant.PHONE_REGEX)
    console.log('校验结果: ' + Validate.email('123'))
    demoApi().then(res => {
      console.log(res.data);
    })
  }

  componentWillUnmount() {
  }

  componentDidShow() {
  }

  componentDidHide() {
  }

  render() {
    return (
      <View className='index'>
        <Text className="primary">Hello Taro!</Text>
        <Demo text="Taro组件"></Demo>
      </View>
    )
  }
}
