// projects/taro-mini-demo/src/pages/index/index.tsx
import {Component} from 'react'
import {Text, View} from '@tarojs/components'
import './index.scss'
import {Pipe, Validate} from "athena-common";
import {CommonUtils} from "athena-utils";
import {Constant} from "athena-constants";
import {Demo} from "athena-components";
import {demoApi} from "../../api/login/demo";

export default class Index extends Component {

  componentWillMount() {
  }

  componentDidMount() {
    console.log('Taro多包复用示例')
    console.log(Pipe.hidePart('18863302302', 'phone'))
    console.log(CommonUtils.randomString(6, 12))
    console.log(Constant.PHONE_REGEX)
    console.log('校验结果: ' + Validate.email('123'))
    demoApi().then(res => {
      console.log(res.data);
    })
  }

  componentWillUnmount() {
  }

  componentDidShow() {
  }

  componentDidHide() {
  }

  render() {
    return (
      <View className='index'>
        <Text className="primary">Hello Taro!</Text>
        <Demo text="Taro组件"></Demo>
      </View>
    )
  }
}

// projects-demo/taro4-mini-vue-demo/src/pages/index/index.vue
<template>
  <view class="index">
    <text>{{ msg }}</text>
    <VueDemoComponent msg="Hello MonoRepo VueComponentDemo"></VueDemoComponent>
  </view>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import './index.scss'
import Taro, { useDidShow, useLoad } from '@tarojs/taro'
import { testHelloJSMonoRepo, testHelloMonoRepo } from 'athena-test'
import { VueDemoComponent } from 'athena-components-vue'
import { demoApi } from '@/api/demo/demo'
import { CommonUtils } from 'athena-utils'
import { Pipe, Validate } from 'athena-common'
import { Constant } from '@athena-constants'

/**
 * 数据定义
 */
const msg = ref('Hello World')


useLoad(() => {
  console.log('Index onLoad')
})

useDidShow(() =>
  testMonoRepo()
)

/**
 * 测试MonoRepo函数
 */
const testMonoRepo = () => {
  // Taro.navigateTo({ url: '/pages/details/details' })

  console.log('Taro多包复用示例')
  testHelloMonoRepo()
  testHelloJSMonoRepo()
  /*  demoApi().then(res => {
      apiData.value = res.data
    })*/

  console.log(CommonUtils.randomString(6, 12))
  console.log(Pipe.hidePart('18863302302', 'phone'))
  console.log(Constant.TOKEN_KEY)
  console.log('校验结果: ' + Validate.email('123'))

}

</script>
