// packages/athena-components/src/demo/demo.tsx
import React from 'react'
import { Text, View } from '@tarojs/components'

import './demo.css'

export interface DemoProps {
  text: string
}

const DemoReactComponent: React.FC<DemoProps> = ({ text }) => {
  return (
    <View className="demo">
      {text} <Text>666</Text>
    </View>
  )
}

export { DemoReactComponent }

// packages/athena-components-vue/src/demo/demo.vue
<template>
  <view class="index">
    <text>{{ msg }}</text>
  </view>
</template>

<script>
import { ref } from 'vue'

export default {
  setup() {
    const msg = ref('athena-components-vue')
    return {
      msg
    }
  },

  onLoad() {
    console.log('athena-components-vue')
  }

}
</script>

<style scoped>
/*每个页面公共css */
</style>
